# Generated by Django 4.1.2 on 2022-10-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="bbs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                ("writer", models.CharField(max_length=100, verbose_name="작성자")),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
            ],
        ),
    ]
